print("----------------------------------")
print("Hi! Let's play madlibs, I need you to fill in the blanks: ")
print("----------------------------------")
print()
print()
print()
city = input("Please provide a town name >>> ")
first_name = input("Please provide a first name >>> ")
nickname = input("Please provide a nickname >>> ")
last_name = input("Please provide a last name >>> ")
drum_competition_name = input("Please provide a drum competition name >>> ")
number = input("Please provide a number amount >>> ")
stick_type_object = input(
    "Please provide a long thin item (ex: baton, snake, etc.) >>> "
)
creature_1 = input("Please provide a creature >>> ")
signature_move = input("Please define a signature trick/move >>> ")
rival_name = input("Please provide a different full name (ex: Deadpool) >>> ")
material = input("Please provide a material >>> ")
percussion_instrument = input("Please provide a percussion instrument >>> ")
food = input("Please provide a food >>> ")
family_member = input("Please provide a family member >>> ")
family_member_name = input("Please provide a family member name >>> ")
trophy_type = input("Please provide a trophy type >>> ")
creature_2 = input("Please provide another creature >>> ")
item = input("Please provide a clothing item >>> ")
print()
print()
print()
print("----------------------------------")
print("Ok, let's see how it turned out!")
print("----------------------------------")
print()
print()
print()
completedStory = print(
    f"In the city of {city}, local drum god {first_name} “{nickname}” {last_name} entered the annual “{drum_competition_name}“ competition with oozing confidence and exactly {number} drumsticks (one was a {stick_type_object}, long story).\n\n{first_name} had been practicing relentlessly on anything they could hit: a drum kit, trash cans, pillows, and once, by mistake, their {creature_1} friend, Marzipan. \n\nTheir signature move, “{signature_move},” usually caused mild property damage but looked pretty sick in slow motion.\n\nAs “{nickname}“ was warming up, they heard the bone chilling sound of {percussion_instrument} and knew that things just got extra serious.\n\nTheir greatest nemesis, {rival_name}, appeared through some fog wearing a cape made of {material} and had unruly hair. {rival_name} was so dedicated to the art of drumming that they only spoke in {percussion_instrument} solos.\n\nDuring the final round of the competition, {first_name} stood for a dramatic drum finale only to trip and land face-first in a kiddie pool of {food} left by their {family_member} {family_member_name}.\n\nUnfortunately, “{nickname}” didn’t win, but neither did {rival_name}! They both got a participation {trophy_type}, and {first_name} got a standing ovation as well as a hateful glance from a {creature_2} wearing a {rival_name} shirt.\n\nTHE END"
)
